### ISSUE TITLE
Maps `bm_c4a3b2` & `bm_c4a3c2` crash server

### ISSUE THREAD

**Issue by lilkingjr1** [ampreeT/SourceCoop#121] opened 2024-04-25 07:19 UTC
Hello! Sorry to bother you, but I just wanted to confirm if this issue I'm having is a real issue or not. Thank you in advance if you decide to take a look :)

My Linux server seems to completely freeze (but not crash with an exit code) every time I load the level `bm_c4a3b2`. When it occurs is somewhat random; sometimes it freezes within a couple seconds of playing the level and sometimes it freezes after 1-2 minutes. It doesn't seem to be caused by any specific player action or part of the level. When the server freezes it no longer takes command-line inputs and the players lose connection and timeout every time.

___

#### Troubleshooting Info:

- Black Mesa Client Version: **Latest**
- Black Mesa Server Version: **Latest** (Maybe this broke with the recent update?)
- SourceCoop Version: **Latest**
- Metamod:Source Build: **1148**
- SourceMod Build: **6960**

Server logs:
```
[STEAM]     Workshop initialized successfully.
[STEAM] subscribed_file_ids.txt not present -- skipping UGC downloads.
[STEAM] VAC secure mode is activated.
Client "Red-Thirten" connected (<Redacted>:27005).
Server waking up from hibernation
CreateInstance called on a point_template that has no templates: interloper_equipment_template
Player "Red-Thirten" joined team spectator
[SRCCOOP] (chat) Difficulty has changed to 2
SV_StartSound:  not precached (0)
[SRCCOOP] Co-op map bm_c4a3b2 has begun
```
(Nothing else prints after this when it crashes)

Please let me know if there's anything else I should provide. Thanks!

**Comment by Alienmario** [comment] 2024-04-25 17:05
It is a real issue we're investigating, thanks for the report.

**Comment by lilkingjr1** [comment] 2024-04-25 18:14
Thank you so much for the prompt reply and for the continued effort to maintain this awesome project :) It's nice to know it's not just my server. I'll let you close this issue whenever you feel it's appropriate. Let me know if there's anything I can do to help.

**Comment by lilkingjr1** [comment] 2024-04-25 19:20
Update: It seems a similar crash occurs with map `bm_c4a3c2` as well.

I decided to wait a little bit after it froze and noticed the server does eventually seg. fault after printing the following logs:
```
WatchDog! Server took too long to process (probably infinite loop).
Host_Error: WatchdogHandler called - server exiting.
/entrypoint.sh: line 89:    44 Segmentation fault      (core dumped) ./srcds_run -console -game bms -secure -ip 0.0.0.0 -port ${SERVER_PORT} +maxplayers ${MAX_PLAYERS} +mp_teamplay 1 +exec server.cfg +map ${STARTING_MAP} -strictportbind -norestart
```

**Comment by lilkingjr1** [comment] 2024-04-25 20:43
Map `bm_c4a4a` (final Nihilanth boss) crashes as well before the server can even start accepting clients.

Logs:
```
ConVarRef sk_suitcharger doesn't point to an existing ConVar
Attempted to create unknown entity type trigger_weapon_dissolve!
Can't init trigger_weapon_dissolve
Attempted to create unknown entity type nihilanth_energy_ball!
NULL Ent in UTIL_PrecacheOther
/entrypoint.sh: line 89:    43 Segmentation fault
```

**Comment by Alienmario** [comment] 2024-04-27 14:41
For the Nihilanth, please test setting this convar before starting the map: mod_forcetouchdata 0
For other maps, a fix has been pushed and will be part of next release.

**Comment by lilkingjr1** [comment] 2024-04-27 19:48
> For other maps, a fix has been pushed and will be part of next release.

Oh awesome! Thank you :)

> For the Nihilanth, please test setting this convar before starting the map: mod_forcetouchdata 0

Yes, `mod_forcetouchdata 0` does seem to fix `bm_c4a4a` (Nihilanth). Could this be added to the next release as an autoexec or something? (Forgive my ignorance)

Lastly, as an unrelated side note: Is it a known issue that the health / suit-charger "pods" and the Gluon Gun "overcharge crystals" do not work in the Xen levels?

**Comment by Alienmario** [comment] 2024-04-27 19:53
Check here: https://github.com/ampreeT/SourceCoop/issues/4#issuecomment-2079682615

You can help us by testing that mod_forcetouchdata has no noticable downsides.

**Comment by rowedahelicon** [comment] 2024-05-04 15:45
> For the Nihilanth, please test setting this convar before starting the map: mod_forcetouchdata 0 For other maps, a fix has been pushed and will be part of next release.

Asking for curiosity's sake, do you know why this is setting is needed and what exactly is the fix for the map otherwise?

Additionally, @lilkingjr1, what version of Linux is the server running on?

**Comment by Alienmario** [comment] 2024-05-04 16:01
It's caused by precaching the Nihilanth model (or part of). Either too soon or too in depth. You can see the stacktrace here https://github.com/ampreeT/SourceCoop/issues/97. It crashes checking if a material is translucent.

**Comment by rowedahelicon** [comment] 2024-05-04 16:45
> It's caused by precaching the Nihilanth model (or part of). Either too soon or too in depth. You can see the stacktrace here #97. It crashes checking if a material is translucent.

Aha, I'm trying to diagnose a similar issue in TF2, exact same crash, exact same fix. I assumed it was something to do with Linux servers.

**Comment by lilkingjr1** [comment] 2024-05-04 21:29
> Additionally, @lilkingjr1, what version of Linux is the server running on?

@rowedahelicon It's running within a `debian:bookworm-slim` Docker container. Not sure what exact OS/kernel version that would be, but I could find out if you want. (I'm running it via [Pterodactyl](https://pterodactyl.io/), if you're at all familiar with that)

**Comment by rowedahelicon** [comment] 2024-05-04 23:35
> > Additionally, @lilkingjr1, what version of Linux is the server running on?
> 
> @rowedahelicon It's running within a `debian:bookworm-slim` Docker container on a Debian Bullseye host. Not sure what exact OS/kernel version that would be, but I could find out if you want. (I'm running it via [Pterodactyl](https://pterodactyl.io/), if you're at all familiar with that)

That would be helpful if it's not too much trouble! I can also take a look at Pterodactyl; I will add that I am also running Debian 12, so I'm going to assume that is what's related.

**Comment by lilkingjr1** [comment] 2024-05-05 02:48
@rowedahelicon No worries about Pterodactyl. It's just a container orchestrator like Portainer, but for game servers; it *should* not have any association with the issue, but just mentioned it to be safe.

The container's userspace OS (libraries, etc.) is 12.5 (Bookworm) but `uname -a` shows the following:
```
Linux <container_id> 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux
```
This means the container is using the host's Bullseye kernel, which I guess is technically expected given Docker, but I guess could raise weird issues in rare cases.

**Comment by Alienmario** [comment] 2024-05-05 15:29
Closing as fixed.

**Closed by Alienmario** 2024-05-05 15:29 UTC
